target 'Segment-Adobe-Analytics_Example' do
  platform :ios, '8.0'
  pod 'Segment-Adobe-Analytics', :path => '../'

  target 'Segment-Adobe-Analytics_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'OCMockito'
  end
end

target 'Segment-Adobe-Analytics_TVOS' do
  platform :tvos, '9.0'
  pod 'Segment-Adobe-Analytics', :path => '../'
end
